### ISSUE TITLE
similar list

### ISSUE THREAD

**Issue by stoeffel** [xgrommx/awesome-functional-reactive#2]
just to let you know, there is https://github.com/stoeffel/awesome-frp-js and https://github.com/stoeffel/awesome-fp-js. maybe we could pick some awesome stuff from each other's lists :smiley:

**Comment by xgrommx** [comment]
@stoeffel this is old repo. I have this https://github.com/xgrommx/awesome-functional-programming and this http://xgrommx.github.io/rx-book/content/resources/index.html

**Comment by stoeffel** [comment]
Cool will check it out.
